- hosts: server
  become: yes
  vars:
    sandbox:
      git_repository: ../beaker
    beaker_server_admin_user: admin
    beaker_server_admin_pass: admin
    beaker_server_email: admin@beaker.local
  tasks:
    - name: disable SELinux as Beaker server prerequisite
      selinux:
        state: disabled
      become: yes

    - name: disable firewalld to allow outside traffic
      service:
        name: firewalld
        enabled: no
        state: stopped
      become: yes

    - import_role:
        name: ../beaker-in-a-box/roles/beaker/setup/repos

    - import_role:
        name: ../beaker-in-a-box/roles/beaker/sandbox/packages

    - name: install pip
      yum:
        name: python2-pip
        state: present

    - name: install Beaker packages in editable mode
      pip:
        name: '{{item}}'
        editable: yes
        state: present
      become: yes
      loop:
        - file:///home/vagrant/beaker/Common
        - file:///home/vagrant/beaker/Server
        - file:///home/vagrant/beaker/Client
        - file:///home/vagrant/beaker/LabController
        - file:///home/vagrant/beaker/IntegrationTests

    - import_role:
        name: ../beaker-in-a-box/roles/beaker/setup/database
      vars:
        databases:
          - beaker
          - beaker_test
          - beaker_migration_test
        users:
          - name: beaker
            password: beaker

    - name: setup /etc/beaker config directory
      file:
        path: /etc/beaker
        state: directory
        owner: vagrant
        group: vagrant
